// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicRankingsAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicRankingsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicRankingsAPI.Models.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<int>("TotalHours")
                        .HasColumnType("integer")
                        .HasColumnName("total_hours");

                    b.HasKey("Id")
                        .HasName("pk_monthly_reports");

                    b.ToTable("monthly_reports", (string)null);
                });

            modelBuilder.Entity("MusicRankingsAPI.Models.MonthlyReportSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthlyReportId")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_report_id");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("pk_monthly_report_songs");

                    b.HasIndex("MonthlyReportId")
                        .HasDatabaseName("ix_monthly_report_songs_monthly_report_id");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_monthly_report_songs_song_id");

                    b.ToTable("monthly_report_songs", (string)null);
                });

            modelBuilder.Entity("MusicRankingsAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("MusicRankingsAPI.Models.MonthlyReportSong", b =>
                {
                    b.HasOne("MusicRankingsAPI.Models.MonthlyReport", "MonthlyReport")
                        .WithMany("MonthlyReportSongs")
                        .HasForeignKey("MonthlyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monthly_reports");

                    b.HasOne("MusicRankingsAPI.Models.Song", "Song")
                        .WithMany("monthlyReportSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_songs");

                    b.Navigation("MonthlyReport");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicRankingsAPI.Models.MonthlyReport", b =>
                {
                    b.Navigation("MonthlyReportSongs");
                });

            modelBuilder.Entity("MusicRankingsAPI.Models.Song", b =>
                {
                    b.Navigation("monthlyReportSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
